---
- name: Remote update tasks
  hosts: all
  tasks:
    - name: Update package cache
      community.general.apk:
        update_cache: yes

    - name: Upgrade all packages
      community.general.apk:
        upgrade: yes
        