---
- name: Remote update tasks
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update package cache
      community.general.apk:
        update_cache: yes

    - name: Upgrade all packages
      community.general.apk:
        upgrade: yes
        